// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_comp_percentuale_create_hook(lv_obj_t * comp)
{
}

void ui_comp_slider_create_hook(lv_obj_t * comp)
{
}
