// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

// COMPONENT slider

lv_obj_t * ui_slider_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_slider;
    cui_slider = lv_arc_create(comp_parent);
    lv_obj_set_width(cui_slider, 142);
    lv_obj_set_height(cui_slider, 150);
    lv_obj_set_x(cui_slider, 0);
    lv_obj_set_y(cui_slider, 3);
    lv_obj_set_align(cui_slider, LV_ALIGN_CENTER);
    lv_arc_set_value(cui_slider, 50);

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_SLIDER_NUM);
    children[UI_COMP_SLIDER_SLIDER] = cui_slider;
    lv_obj_add_event_cb(cui_slider, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_slider, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_slider_create_hook(cui_slider);
    return cui_slider;
}

