// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

// COMPONENT percentuale

lv_obj_t * ui_percentuale_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_percentuale;
    cui_percentuale = lv_label_create(comp_parent);
    lv_obj_set_width(cui_percentuale, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_percentuale, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(cui_percentuale, LV_ALIGN_CENTER);

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_PERCENTUALE_NUM);
    children[UI_COMP_PERCENTUALE_PERCENTUALE] = cui_percentuale;
    lv_obj_add_event_cb(cui_percentuale, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_percentuale, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_percentuale_create_hook(cui_percentuale);
    return cui_percentuale;
}

