// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _UI_COMP_PERCENTUALE_H
#define _UI_COMP_PERCENTUALE_H

#include "ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT percentuale
#define UI_COMP_PERCENTUALE_PERCENTUALE 0
#define _UI_COMP_PERCENTUALE_NUM 1
lv_obj_t * ui_percentuale_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
