// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * uic_percentuale1;
lv_obj_t * uic_slider1;
lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_slider1 = NULL;
lv_obj_t * ui_percentuale1 = NULL;
// event funtions

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_slider1 = ui_slider_create(ui_Screen1);
    lv_obj_set_width(ui_slider1, 135);
    lv_obj_set_height(ui_slider1, 135);
    lv_obj_set_x(ui_slider1, 0);
    lv_obj_set_y(ui_slider1, 1);
    lv_obj_set_align(ui_slider1, LV_ALIGN_CENTER);
    lv_obj_set_style_arc_width(ui_slider1, 7, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_slider1, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_slider1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_slider1, 7, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_slider1, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_slider1, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_percentuale1 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_percentuale1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_percentuale1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_percentuale1, LV_ALIGN_CENTER);
    lv_obj_set_style_text_font(ui_percentuale1, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    uic_slider1 = ui_slider1;
    uic_percentuale1 = ui_percentuale1;

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    uic_slider1 = NULL;
    ui_slider1 = NULL;
    uic_percentuale1 = NULL;
    ui_percentuale1 = NULL;

}
