// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * uic_percentuale3;
lv_obj_t * uic_slider3;
lv_obj_t * ui_Screen3 = NULL;
lv_obj_t * ui_slider3 = NULL;
lv_obj_t * ui_percentuale3 = NULL;
// event funtions

// build funtions

void ui_Screen3_screen_init(void)
{
    ui_Screen3 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_slider3 = ui_slider_create(ui_Screen3);
    lv_obj_set_width(ui_slider3, 135);
    lv_obj_set_height(ui_slider3, 135);
    lv_obj_set_x(ui_slider3, 0);
    lv_obj_set_y(ui_slider3, 1);
    lv_obj_set_align(ui_slider3, LV_ALIGN_CENTER);
    lv_obj_set_style_arc_width(ui_slider3, 7, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_slider3, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_slider3, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_slider3, 7, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_slider3, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_slider3, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_percentuale3 = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_percentuale3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_percentuale3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_percentuale3, LV_ALIGN_CENTER);
    lv_obj_set_style_text_font(ui_percentuale3, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    uic_slider3 = ui_slider3;
    uic_percentuale3 = ui_percentuale3;

}

void ui_Screen3_screen_destroy(void)
{
    if(ui_Screen3) lv_obj_del(ui_Screen3);

    // NULL screen variables
    ui_Screen3 = NULL;
    uic_slider3 = NULL;
    ui_slider3 = NULL;
    uic_percentuale3 = NULL;
    ui_percentuale3 = NULL;

}
